[package]
name = "wow_wiki_bot"
version = "0.1.0"
authors = ["Alexander <you@example.com>"]

[dependencies]
hyper = "0.10.8"
hyper-rustls = "0.6.0"
url = "1.7.1"
rustc-serialize = "0.3.24"
serde_json = "0.9.10"
serde = "0.9.14"
serde_derive = "0.9.14"